version = 0.1
[default.deploy.parameters]
stack_name = "product-serverless-dev"
resolve_s3 = true
s3_prefix = "product-serverless-dev"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
